"use client";

import {
  CalendarClock, CheckCircle2, ChevronRight, ClipboardList,
  FileDown, Plus, Save, ShoppingCart, Trash2, TrendingDown, X,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { Item } from "@/data/inventory";
import { getStockHealth } from "@/components/management-views";

type BatchRecord = { id: string; itemId: string; item: string; batch: string; received: string; produced: string; expiry: string; qty: number; unit: string };
const seedBatches: BatchRecord[] = [
  { id: "BAT-001", itemId: "1", item: "Fresh Milk Pasteurisasi 1 L", batch: "FM-0906-A", received: "2026-09-06", produced: "2026-09-04", expiry: "2026-09-11", qty: 18, unit: "Kotak" },
  { id: "BAT-002", itemId: "14", item: "Telur Ayam", batch: "EG-0905-B", received: "2026-09-05", produced: "2026-09-03", expiry: "2026-09-18", qty: 6, unit: "Tray" },
  { id: "BAT-003", itemId: "36", item: "Salmon Fillet", batch: "SLM-0830", received: "2026-08-30", produced: "2026-08-29", expiry: "2026-09-08", qty: 5, unit: "Kg" },
  { id: "BAT-004", itemId: "72", item: "House-made BBQ Sauce", batch: "BBQ-0902", received: "2026-09-02", produced: "2026-09-02", expiry: "2026-09-15", qty: 9, unit: "Liter" },
  { id: "BAT-005", itemId: "90", item: "Vanilla Syrup 700 ml", batch: "VNL-0826", received: "2026-08-26", produced: "2026-07-12", expiry: "2027-07-12", qty: 13, unit: "Botol" },
];

export type AuditEntry = { id: string; time: string; user: string; action: string; detail: string; module: string };
export const seedAudit: AuditEntry[] = [
  { id: "AUD-001", time: "2026-09-06T08:42:00", user: "Dimas Riyanto", action: "Barang masuk", detail: "Fresh Milk +24 Kotak", module: "Transaksi" },
  { id: "AUD-002", time: "2026-09-06T08:18:00", user: "Fajar Akbar", action: "Barang keluar", detail: "House Blend −6 Kg", module: "Transaksi" },
  { id: "AUD-003", time: "2026-09-05T16:05:00", user: "Rani Putri", action: "Purchase order", detail: "PO-2026-014 diajukan", module: "Pembelian" },
];

export function BatchFefoView({ items, onAudit }: { items: Item[]; onAudit: (action: string, detail: string, module: string) => void }) {
  const [batches, setBatches] = useStoredList("stockflow-batches-v1", seedBatches);
  const [filter, setFilter] = useState("Semua");
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ itemId: items[0]?.id ?? "", batch: "", received: "2026-09-09", produced: "2026-09-09", expiry: "2026-09-16", qty: "" });
  const selected = items.find((item) => item.id === form.itemId);
  const sorted = useMemo(() => batches.toSorted((a, b) => a.expiry.localeCompare(b.expiry)).filter((batch) => {
    const days = daysUntil(batch.expiry);
    if (filter === "7 hari") return days >= 0 && days <= 7;
    if (filter === "14 hari") return days >= 0 && days <= 14;
    if (filter === "30 hari") return days >= 0 && days <= 30;
    if (filter === "Kedaluwarsa") return days < 0;
    return true;
  }), [batches, filter]);
  function submit(event: React.FormEvent) { event.preventDefault(); if (!selected) return; const record: BatchRecord = { id: `BAT-${String(batches.length + 1).padStart(3, "0")}`, itemId: selected.id, item: selected.name, batch: form.batch, received: form.received, produced: form.produced, expiry: form.expiry, qty: Number(form.qty), unit: selected.unit }; setBatches((current) => [record, ...current]); onAudit("Batch ditambahkan", `${record.item} · ${record.batch}`, "Batch & FEFO"); setShowForm(false); }
  return <div className="page-content"><section className="page-heading"><div><h2>Batch &amp; FEFO</h2><p>Prioritaskan penggunaan bahan berdasarkan tanggal kedaluwarsa terdekat.</p></div><button className="primary" onClick={() => setShowForm(true)}><Plus size={17}/> Tambah batch</button></section>
    <section className="expiry-stats"><Metric title="Kedaluwarsa ≤7 hari" value={batches.filter((item) => { const days = daysUntil(item.expiry); return days >= 0 && days <= 7; }).length} tone="red"/><Metric title="Kedaluwarsa ≤14 hari" value={batches.filter((item) => { const days = daysUntil(item.expiry); return days >= 0 && days <= 14; }).length} tone="orange"/><Metric title="Kedaluwarsa ≤30 hari" value={batches.filter((item) => { const days = daysUntil(item.expiry); return days >= 0 && days <= 30; }).length} tone="purple"/><Metric title="Total batch aktif" value={batches.length} tone="green"/></section>
    <div className="filter-pills">{["Semua", "7 hari", "14 hari", "30 hari", "Kedaluwarsa"].map((item) => <button key={item} className={filter === item ? "active" : ""} onClick={() => setFilter(item)}>{item}</button>)}</div>
    <article className="panel table-panel"><div className="fefo-note"><CalendarClock/><div><strong>Urutan FEFO aktif</strong><p>Batch dengan masa simpan paling pendek tampil paling atas dan harus digunakan lebih dahulu.</p></div></div><div className="table-scroll"><table><thead><tr><th>Prioritas</th><th>Barang</th><th>Nomor batch</th><th>Diterima</th><th>Produksi</th><th>Kedaluwarsa</th><th>Sisa waktu</th><th>Jumlah</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{sorted.map((batch, index) => { const days = daysUntil(batch.expiry); const status = expiryStatus(days); return <tr key={batch.id}><td><span className="fefo-rank">#{index + 1}</span></td><td><strong>{batch.item}</strong><small className="table-meta">{batch.id}</small></td><td>{batch.batch}</td><td>{formatDate(batch.received)}</td><td>{formatDate(batch.produced)}</td><td>{formatDate(batch.expiry)}</td><td><b>{days < 0 ? `${Math.abs(days)} hari lewat` : `${days} hari`}</b></td><td>{batch.qty} {batch.unit}</td><td><span className={`status ${status.tone}`}>{status.label}</span></td><td><button className="table-action danger" onClick={() => setBatches((current) => current.filter((item) => item.id !== batch.id))}><Trash2/></button></td></tr>; })}</tbody></table></div></article>
    {showForm && <Modal title="Tambah batch penerimaan" subtitle="Lengkapi produksi dan kedaluwarsa untuk menjalankan FEFO." onClose={() => setShowForm(false)}><form onSubmit={submit}><div className="form-grid"><label>Nama barang<select value={form.itemId} onChange={(e) => setForm({ ...form, itemId: e.target.value })}>{items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field label="Nomor batch" value={form.batch} onChange={(value) => setForm({ ...form, batch: value })}/><Field label="Tanggal diterima" value={form.received} type="date" onChange={(value) => setForm({ ...form, received: value })}/><Field label="Tanggal produksi" value={form.produced} type="date" onChange={(value) => setForm({ ...form, produced: value })}/><Field label="Tanggal kedaluwarsa" value={form.expiry} type="date" onChange={(value) => setForm({ ...form, expiry: value })}/><Field label={`Jumlah (${selected?.unit ?? "unit"})`} value={form.qty} type="number" onChange={(value) => setForm({ ...form, qty: value })}/></div><Actions onCancel={() => setShowForm(false)} label="Simpan batch"/></form></Modal>}
  </div>;
}

type PurchaseOrder = { id: string; created: string; supplier: string; itemId: string; item: string; qty: number; unit: string; price: number; status: "Draft" | "Diajukan" | "Disetujui" | "Dipesan" | "Diterima"; eta: string };
const statusFlow: PurchaseOrder["status"][] = ["Draft", "Diajukan", "Disetujui", "Dipesan", "Diterima"];

export function PurchaseOrdersView({ items, onAudit }: { items: Item[]; onAudit: (action: string, detail: string, module: string) => void }) {
  const initial = items.filter((item) => getStockHealth(item).restock > 0).slice(0, 3).map((item, index): PurchaseOrder => ({ id: `PO-2026-${String(14 + index).padStart(3, "0")}`, created: "2026-09-09", supplier: item.supplier.split("/")[0].trim(), itemId: item.id, item: item.name, qty: getStockHealth(item).restock, unit: item.unit, price: item.price, status: index === 0 ? "Diajukan" : "Draft", eta: `2026-09-${12 + index}` }));
  const [orders, setOrders] = useStoredList("stockflow-purchase-orders-v1", initial);
  const [showForm, setShowForm] = useState(false);
  const restockItems = items.filter((item) => getStockHealth(item).restock > 0);
  const [form, setForm] = useState({ itemId: restockItems[0]?.id ?? items[0]?.id ?? "", supplier: "", qty: "", price: "", eta: "2026-09-10" });
  const selected = items.find((item) => item.id === form.itemId);
  function nextStatus(order: PurchaseOrder) { const next = statusFlow[Math.min(statusFlow.indexOf(order.status) + 1, statusFlow.length - 1)]; setOrders((current) => current.map((item) => item.id === order.id ? { ...item, status: next } : item)); onAudit("Status PO diperbarui", `${order.id}: ${order.status} → ${next}`, "Pembelian"); }
  function submit(event: React.FormEvent) { event.preventDefault(); if (!selected) return; const order: PurchaseOrder = { id: `PO-2026-${String(orders.length + 14).padStart(3, "0")}`, created: "2026-09-09", supplier: form.supplier || selected.supplier.split("/")[0].trim(), itemId: selected.id, item: selected.name, qty: Number(form.qty) || getStockHealth(selected).restock, unit: selected.unit, price: Number(form.price) || selected.price, status: "Draft", eta: form.eta }; setOrders((current) => [order, ...current]); onAudit("Purchase order dibuat", `${order.id} · ${order.item}`, "Pembelian"); setShowForm(false); }
  const total = orders.reduce((sum, order) => sum + order.qty * order.price, 0);
  const quoteItem = restockItems[0];
  return <div className="page-content"><section className="page-heading"><div><h2>Purchase order</h2><p>Ubah kebutuhan restock menjadi pesanan pembelian yang terkontrol.</p></div><button className="primary" onClick={() => setShowForm(true)}><Plus size={17}/> Buat PO</button></section>
    <section className="management-stats"><div><ShoppingCart/><span><small>Total purchase order</small><strong>{orders.length}</strong></span></div><div><ClipboardList/><span><small>Menunggu proses</small><strong>{orders.filter((item) => item.status !== "Diterima").length}</strong></span></div><div><TrendingDown/><span><small>Nilai pemesanan</small><strong>{formatMoney(total)}</strong></span></div></section>
    <article className="panel table-panel"><div className="table-scroll"><table><thead><tr><th>Purchase order</th><th>Supplier</th><th>Item</th><th>Jumlah</th><th>Harga</th><th>Total</th><th>Estimasi tiba</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><strong>{order.id}</strong><small className="table-meta">{formatDate(order.created)}</small></td><td>{order.supplier}</td><td>{order.item}</td><td>{order.qty} {order.unit}</td><td>{formatMoney(order.price)}</td><td><b>{formatMoney(order.qty * order.price)}</b></td><td>{formatDate(order.eta)}</td><td><span className={`po-status ${order.status.toLowerCase()}`}>{order.status}</span></td><td><button className="table-action" disabled={order.status === "Diterima"} onClick={() => nextStatus(order)}>{order.status === "Diterima" ? "Selesai" : <>{statusFlow[statusFlow.indexOf(order.status) + 1]} <ChevronRight/></>}</button></td></tr>)}</tbody></table></div></article>
    {quoteItem && <article className="panel quote-panel"><div className="section-title"><div><h3>Perbandingan harga supplier</h3><p>Simulasi quotation untuk {quoteItem.name}.</p></div></div><div className="quote-grid">{[{ name: quoteItem.supplier.split("/")[0], price: quoteItem.price, lead: "2–3 hari" }, { name: "Lotte Grosir", price: Math.round(quoteItem.price * 1.06), lead: "1–2 hari" }, { name: "Supplier Lokal", price: Math.round(quoteItem.price * .96), lead: "3–4 hari" }].map((quote, index) => <div key={quote.name} className={index === 2 ? "best" : ""}><span>{index === 2 ? "Harga terbaik" : "Quotation"}</span><strong>{quote.name}</strong><b>{formatMoney(quote.price)}</b><small>Lead time {quote.lead}</small></div>)}</div></article>}
    {showForm && <Modal title="Buat purchase order" subtitle="Item prioritas restock sudah disaring otomatis." onClose={() => setShowForm(false)}><form onSubmit={submit}><div className="form-grid"><label>Item<select value={form.itemId} onChange={(e) => { const item = items.find((entry) => entry.id === e.target.value); setForm({ ...form, itemId: e.target.value, supplier: item?.supplier.split("/")[0].trim() ?? "", qty: item ? String(getStockHealth(item).restock) : "", price: item ? String(item.price) : "" }); }}>{restockItems.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field label="Supplier" value={form.supplier} onChange={(value) => setForm({ ...form, supplier: value })}/><Field label={`Jumlah (${selected?.unit ?? "unit"})`} value={form.qty || (selected ? String(getStockHealth(selected).restock) : "")} type="number" onChange={(value) => setForm({ ...form, qty: value })}/><Field label="Harga satuan" value={form.price || String(selected?.price ?? "")} type="number" onChange={(value) => setForm({ ...form, price: value })}/><Field label="Estimasi tiba" value={form.eta} type="date" onChange={(value) => setForm({ ...form, eta: value })}/></div><Actions onCancel={() => setShowForm(false)} label="Simpan sebagai draft"/></form></Modal>}
  </div>;
}

type WasteRecord = { id: string; date: string; itemId: string; item: string; qty: number; unit: string; reason: string; loss: number };
const seedWaste: WasteRecord[] = [{ id: "WST-001", date: "2026-09-05", itemId: "1", item: "Fresh Milk Pasteurisasi 1 L", qty: 2, unit: "Kotak", reason: "Kedaluwarsa", loss: 42000 }];

export function WasteView({ items, onWaste, onAudit }: { items: Item[]; onWaste: (itemId: string, qty: number) => string | null; onAudit: (action: string, detail: string, module: string) => void }) {
  const [records, setRecords] = useStoredList("stockflow-waste-v1", seedWaste);
  const [form, setForm] = useState({ itemId: items[0]?.id ?? "", qty: "", reason: "Kedaluwarsa", date: "2026-09-09" });
  const [message, setMessage] = useState("");
  const selected = items.find((item) => item.id === form.itemId);
  function submit(event: React.FormEvent) { event.preventDefault(); if (!selected) return; const qty = Number(form.qty); const error = onWaste(selected.id, qty); if (error) { setMessage(error); return; } const record: WasteRecord = { id: `WST-${String(records.length + 1).padStart(3, "0")}`, date: form.date, itemId: selected.id, item: selected.name, qty, unit: selected.unit, reason: form.reason, loss: qty * selected.price }; setRecords((current) => [record, ...current]); onAudit("Waste dicatat", `${record.item} −${qty} ${record.unit}`, "Waste"); setMessage("Waste berhasil dicatat dan stok telah dikurangi."); setForm((current) => ({ ...current, qty: "" })); }
  const totalLoss = records.reduce((sum, item) => sum + item.loss, 0);
  return <div className="page-content"><section className="page-heading"><div><h2>Waste &amp; kerugian</h2><p>Catat bahan rusak, basi, kedaluwarsa, atau selisih operasional.</p></div><button className="secondary" onClick={() => window.print()}><FileDown size={17}/> Cetak laporan</button></section><section className="waste-layout"><form className="panel entry-form" onSubmit={submit}><div className="section-title"><div><h3>Catat waste</h3><p>Nilai kerugian dihitung dari harga estimasi barang.</p></div></div><div className="form-grid"><label>Barang<select value={form.itemId} onChange={(e) => setForm({ ...form, itemId: e.target.value })}>{items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><Field label={`Jumlah (${selected?.unit ?? "unit"})`} value={form.qty} type="number" onChange={(value) => setForm({ ...form, qty: value })}/><label>Alasan<select value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })}><option>Kedaluwarsa</option><option>Rusak</option><option>Basi</option><option>Salah produksi</option><option>Selisih opname</option></select></label><Field label="Tanggal" value={form.date} type="date" onChange={(value) => setForm({ ...form, date: value })}/></div>{message && <div className={message.includes("berhasil") ? "form-message success" : "form-message error"}>{message}</div>}<button className="primary"><Save size={16}/> Simpan waste</button></form><article className="panel loss-card"><span>Total kerugian tercatat</span><strong>{formatMoney(totalLoss)}</strong><p>{records.reduce((sum, item) => sum + item.qty, 0)} unit dari {records.length} kejadian</p><TrendingDown/></article></section><article className="panel table-panel history-panel"><div className="table-scroll"><table><thead><tr><th>Tanggal</th><th>Barang</th><th>Jumlah</th><th>Alasan</th><th>Nilai kerugian</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td>{formatDate(record.date)}</td><td><strong>{record.item}</strong><small className="table-meta">{record.id}</small></td><td>{record.qty} {record.unit}</td><td><span className="status out">{record.reason}</span></td><td><b>{formatMoney(record.loss)}</b></td></tr>)}</tbody></table></div></article></div>;
}

export function AuditLogView({ logs }: { logs: AuditEntry[] }) { return <div className="page-content"><section className="page-heading"><div><h2>Audit log</h2><p>Jejak aktivitas pengguna untuk transparansi dan pemeriksaan internal.</p></div><button className="secondary" onClick={() => exportAudit(logs)}><FileDown size={17}/> Export CSV</button></section><article className="panel timeline-panel">{logs.map((log) => <div className="audit-row" key={log.id}><span><CheckCircle2/></span><div><strong>{log.action}</strong><p>{log.detail}</p><small>{log.user} · {log.module}</small></div><time>{formatDateTime(log.time)}</time></div>)}</article></div>; }

function Metric({ title, value, tone }: { title: string; value: number; tone: string }) { return <article className={`expiry-metric ${tone}`}><span>{title}</span><strong>{value}</strong></article>; }
function Modal({ title, subtitle, onClose, children }: { title: string; subtitle: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal" onMouseDown={(event) => event.stopPropagation()}><div className="modal-head"><div><h2>{title}</h2><p>{subtitle}</p></div><button onClick={onClose} aria-label="Tutup"><X/></button></div>{children}</section></div>; }
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label>{label}<input required type={type} min={type === "number" ? 1 : undefined} value={value} onChange={(event) => onChange(event.target.value)}/></label>; }
function Actions({ onCancel, label }: { onCancel: () => void; label: string }) { return <div className="modal-actions"><button type="button" className="secondary" onClick={onCancel}>Batal</button><button className="primary"><Save size={16}/>{label}</button></div>; }
function useStoredList<T>(key: string, initial: T[]) { const [value, setValue] = useState(initial); useEffect(() => { const stored = localStorage.getItem(key); if (!stored) return; const frame = requestAnimationFrame(() => setValue(JSON.parse(stored))); return () => cancelAnimationFrame(frame); }, [key]); useEffect(() => localStorage.setItem(key, JSON.stringify(value)), [key, value]); return [value, setValue] as const; }
function daysUntil(date: string) { const today = new Date("2026-09-09T00:00:00+08:00"); return Math.ceil((new Date(`${date}T00:00:00+08:00`).getTime() - today.getTime()) / 86400000); }
function expiryStatus(days: number) { if (days < 0) return { label: "Kedaluwarsa", tone: "out" }; if (days <= 7) return { label: "Kritis", tone: "restock" }; if (days <= 14) return { label: "Segera digunakan", tone: "low" }; return { label: "Aman", tone: "safe" }; }
function formatDate(value: string) { return new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(`${value}T00:00:00`)); }
function formatDateTime(value: string) { return new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Asia/Makassar" }).format(new Date(value)); }
function formatMoney(value: number) { return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value); }
function exportAudit(logs: AuditEntry[]) { const rows = [["Waktu", "Pengguna", "Modul", "Aktivitas", "Detail"], ...logs.map((item) => [item.time, item.user, item.module, item.action, item.detail])]; const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob(["\ufeff", csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "stockflow-audit-log.csv"; anchor.click(); URL.revokeObjectURL(url); }
